### ISSUE TITLE
Let's create a "first time only" tag for the newcomers

### ISSUE THREAD

**Issue by nikitakoselev** [openedx/paragon#1530]
A lot of people are interested in contributing to this project, but they might not know how to start.
Let's create a "first time only" kind of a tag and let's also create a CONTRIBUTING.md file, 
with somebody more experienced than I will describe the main ways of contributing to the project.

It also won't hurt to raise a few example issues tagged "first time only".

**Comment by adamstankiewicz** [comment]
FWIW, there is also a link to a "Contributing" guide from the Paragon [documentation website](https://paragon-openedx.netlify.app/):

<img width="150" alt="image" src="https://user-images.githubusercontent.com/2828721/215226692-9664dcf8-ca69-4da7-863a-ad2ddc5409b1.png">

But I believe it does require you to have access to the Open edX Confluence.

**Comment by adamstankiewicz** [comment]
Opting to close this issue as we have created a "good first issue" label, [this PR](https://github.com/openedx/paragon/issues/1971) will be merging shortly to add CONTRIBUTING.md file, and I split out a follow-on task of ensuring the "Contributing" link in the documentation website (shown above) links to a page on the documentation website itself rather than leading to Confluence, which requires authentication.
