### ISSUE TITLE
Re-enable the openedx/cla check on Paragon

### ISSUE THREAD

**Issue by feanil** [openedx/paragon#1752]
* Do this in a way that doesn't break the semantic-release tooling or fix the semantic release tooling to work with this requirement.
* @adamstankiewicz can help pair on this.

**Comment by adamstankiewicz** [comment]
@feanil and @adamstankiewicz paired on a solution to unblock Paragon releases, with the side effect of temporarily breaking the CHANGELOG and package.json updates (i.e., they won't currently get committed back to `master`). We have triaged this issue and plan to have a solution to re-implement the functionality in a different way (see https://github.com/openedx/paragon/issues/1768).

Closing this issue, since the `openedx/cla` check is enabled again.
