### ISSUE TITLE
Tabs "More..." dropdown seems to expand beyond `Tabs` bottom border

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2445]
## Bugs

When hovering over the "More..." dropdown in the `Tabs` component ([docs](https://paragon-openedx.netlify.app/components/tabs/#responsive-support)), it appears the button expands beyond the width of the light gray bottom border underneath all the `Tabs` options.

<img width="940" alt="image" src="https://github.com/openedx/paragon/assets/2828721/8f99a2a8-1be2-4cfe-aa7a-2bc1a423b7ab">

<img width="948" alt="image" src="https://github.com/openedx/paragon/assets/2828721/1724b124-646a-48bc-a7a2-22d096efcc38">

```[tasklist]
### Tasks
- [ ] Ensure the "More..." button does not expand beyond the `Tabs` width.
```

**Comment by PKulkoRaccoonGang** [comment]
For a deeper understanding of this behavior, let's examine the Paragon hook [useIndexOfLastVisibleChild](https://paragon-openedx.netlify.app/components/hooks/useindexoflastvisiblechild/). Its performance is reliant on the window's width, which is calculated using the internal React hook `useLayoutEffect` and recalculated whenever the window width changes. The issue arises from the presence of two loaded themes (OpenEdx and Brand) on the [Paragon documentation site](https://paragon-openedx.netlify.app/), each having different container widths (e.g., OpenEdx theme - 1270 and Brand theme - 1248).

Upon the initial page load, the OpenEdx theme is loaded, and the window width is calculated and remains constant. If we switch to the Brand theme, the original window width persists without updating. Consequently, the behavior associated with the initially selected Brand theme remains the same because the page initially loads with the OpenEdx theme and is later replaced by the Brand theme.

This behavior is unique to the Paragon documentation site due to the presence of multiple theme loading and a dynamic page container. However, this issue doesn't extend to consuming MFEs, as they load only one theme during page load. 
@adamstankiewicz, what are your thoughts?
