### ISSUE TITLE
Invalid filter in Usage Insights table

### ISSUE THREAD

**Issue by viktorrusakov** [openedx/paragon#2694]
When going to [Usage Insights page](https://paragon-openedx.netlify.app/insights) it displays strange `Paragon` filter

![image](https://github.com/openedx/paragon/assets/52399399/575a46a1-9794-4da0-9119-989a8a17a7e8)

It appears that some projects import all of Paragon components in tests as follows
![image](https://github.com/openedx/paragon/assets/52399399/a9cb0c4e-9337-48d2-a35e-1d77ac2d9852)
which confuses our dependent usage analyzer.

This can be solved in one of the following ways:
1. Improve dependent analyzer to understand such imports and extract the actual used components in the file (will likely require too much effort)
2. Ignore files with such imports (such imports will probably only occur in tests and I don't think we particularly care how our components are used in tests)
3. Ignore all test files (again, do we care how often Paragon components are used in tests? If not, maybe we can just skip such files)

**Comment by adamstankiewicz** [comment]
We will close this as a won't do, because `import * from '@edx/paragon';` is technically supported and having it show up in Usage Insights is good discoverability for when consumers do these imports.

If consumers want to import Paragon in this way for their tests (all the existing use cases thus far), this is likely OK.
