### ISSUE TITLE
[discovery] Attempt to get the semantic release version preview on CI working again

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#2778]

**Comment by viktorrusakov** [comment]
@adamstankiewicz I'm closing this because there is now way we can make semantic release work for all PRs right now. I've tried a bunch of stuff but it all comes down to the fact that we cannot preview new semantic release version on the PRs opened from forked repositories because `semantic-release` package requires push access to the repository even when you use `--dry-run` option (do not ask me why, I have no idea why they made it this way...), which we obviously do not have.

I could make preview work only on PRs from upstream repository, but that's not enough considering that majority of PRs we have are coming from RacoonGang's fork, so this CI step would just fail on most PRs (and for other open-source contributors as well)

I've removed this step from our pipeline as a result (I don't think it was particularly useful anyway to be honest).
